config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :empresas

  resources :ubicaciones

  resources :habilidades

  resources :categorias

  resources :experiencias

  resources :socios

  resources :laborales

  resources :permisos

  resources :perfiles

  resources :direcciones

  resources :usuarios

  resources :comunas

  resources :telefonos

  resources :slas

 resources :contratos do
     resources :calidades
  end 

 root 'index#index'
 

end

app/models/calidad.rb
class Calidad < ActiveRecord::Base
  belongs_to :sla
  belongs_to :contrato

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  belongs_to :laboral
end

app/models/comuna.rb
class Comuna < ActiveRecord::Base
	belongs_to :direccion
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
  belongs_to :usuario
  has_many :calidades
  has_many :slas, through: :calidades


end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :comuna
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
end

app/models/experiencia.rb
class Experiencia < ActiveRecord::Base
  belongs_to :laboral
  belongs_to :empresa
end

app/models/habilidad.rb
class Habilidad < ActiveRecord::Base
  belongs_to :usuario

# para aplicarlo en caso de que el usuario quiera crear otra habilidad (en no se ocupa actualmente)
  def habilidad_nombre
  	habilidad.try(:habilidad)
  end

  def habilidad_nombre=(habilidad)
  	  	self.habilidad = Habilidad.find_or_create_by_habilidad(habilidad) if habilidad.present?
  	  	#find_or_create_by_name
  end

end

app/models/laboral.rb
class Laboral < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
  belongs_to :empresa
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base
  belongs_to :perfil
end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
end

app/models/sla.rb
class Sla < ActiveRecord::Base
	  has_many :calidades
 	  has_many :contrato, through: :calidades
end

app/models/socio.rb
class Socio < ActiveRecord::Base
  belongs_to :usuario
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :usuario
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion

  def direccion_choose
  	direccion.try(:direccion)
  end

  def direccion_choose=(direccion)
  	  	self.direccion = Direccion.find_by_direccion(direccion) if direccion.present?
  	  	#find_or_create_by_name
  end

end

app/controllers/experiencias_controller.rb
class ExperienciasController < ApplicationController
  before_action :set_experiencia, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /experiencias
  # GET /experiencias.json
  def index
    @experiencias = Experiencia.all
  end

  # GET /experiencias/1
  # GET /experiencias/1.json
  def show
  end

  # GET /experiencias/new
  def new
    @experiencia = Experiencia.new
  end

  # GET /experiencias/1/edit
  def edit
  end

  # POST /experiencias
  # POST /experiencias.json
  def create
    @experiencia = Experiencia.new(experiencia_params)

    respond_to do |format|
      if @experiencia.save
        format.html { redirect_to @experiencia, notice: 'Experiencia fue exitosamente creado.' }
        format.json { render :show, status: :created, location: @experiencia }
      else
        format.html { render :new }
        format.json { render json: @experiencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiencias/1
  # PATCH/PUT /experiencias/1.json
  def update
    respond_to do |format|
      if @experiencia.update(experiencia_params)
        format.html { redirect_to @experiencia, notice: 'Experiencia  fue exitosamente actualizado.' }
        format.json { render :show, status: :ok, location: @experiencia }
      else
        format.html { render :edit }
        format.json { render json: @experiencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiencias/1
  # DELETE /experiencias/1.json
  def destroy
    @experiencia.destroy
    respond_to do |format|
      format.html { redirect_to experiencias_url, notice: 'Experiencia fue exitosamente destruido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiencia
      @experiencia = Experiencia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiencia_params
      params.require(:experiencia).permit(:experiencia_id, :fechaInicio, :fechaFin, :rubro, :cargo, :descripcion, :laboral_id, :empresa_id)
    end
end

app/helpers/comunas_helper.rb
module ComunasHelper
end

app/helpers/experiencias_helper.rb
module ExperienciasHelper
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/helpers/slas_helper.rb
module SlasHelper
end

app/helpers/socios_helper.rb
module SociosHelper
end

app/views/experiencias/_form.html.erb
<%= form_for @experiencia, :html => { :class => "form-horizontal experiencia" } do |f| %>

    <% if @experiencia.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@experiencia.errors.count, "error") %> prohibited this experiencia from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @experiencia.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :experiencia_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :experiencia_id, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:experiencia_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :fechaInicio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fechaInicio, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:fechaInicio]) %>
  </div>
  <div class="control-group">
    <%= f.label :fechaFin, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fechaFin, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:fechaFin]) %>
  </div>
  <div class="control-group">
    <%= f.label :rubro, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rubro, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:rubro]) %>
  </div>
  <div class="control-group">
    <%= f.label :cargo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cargo, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:cargo]) %>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descripcion, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:descripcion]) %>
  </div>
  <div class="control-group">
    <%= f.label :laboral_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :laboral_id, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:laboral_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :empresa_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :empresa_id, :class => 'form-control' %>
    </div>
    <%= error_span(@experiencia[:empresa_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            experiencias_path, :class => 'btn btn-default' %>

<% end %>

app/views/experiencias/edit.html.erb
<%- model_class = Experiencia -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/experiencias/index.html.erb
<%- model_class = Experiencia -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:experiencia_id) %></th>
      <th><%= model_class.human_attribute_name(:fechaInicio) %></th>
      <th><%= model_class.human_attribute_name(:fechaFin) %></th>
      <th><%= model_class.human_attribute_name(:rubro) %></th>
      <th><%= model_class.human_attribute_name(:cargo) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:laboral_id) %></th>
      <th><%= model_class.human_attribute_name(:empresa_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @experiencias.each do |experiencia| %>
      <tr>
        <td><%= link_to experiencia.id, experiencia_path(experiencia) %></td>
        <td><%= experiencia.experiencia_id %></td>
        <td><%= experiencia.fechaInicio %></td>
        <td><%= experiencia.fechaFin %></td>
        <td><%= experiencia.rubro %></td>
        <td><%= experiencia.cargo %></td>
        <td><%= experiencia.descripcion %></td>
        <td><%= experiencia.laboral_id %></td>
        <td><%= experiencia.empresa_id %></td>
        <td><%=l experiencia.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_experiencia_path(experiencia), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      experiencia_path(experiencia),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_experiencia_path,
            :class => 'btn btn-primary' %>

app/views/experiencias/new.html.erb
<%- model_class = Experiencia -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/experiencias/show.html.erb
<%- model_class = Experiencia -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:experiencia_id) %>:</strong></dt>
  <dd><%= @experiencia.experiencia_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fechaInicio) %>:</strong></dt>
  <dd><%= @experiencia.fechaInicio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fechaFin) %>:</strong></dt>
  <dd><%= @experiencia.fechaFin %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rubro) %>:</strong></dt>
  <dd><%= @experiencia.rubro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cargo) %>:</strong></dt>
  <dd><%= @experiencia.cargo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @experiencia.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:laboral_id) %>:</strong></dt>
  <dd><%= @experiencia.laboral_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:empresa_id) %>:</strong></dt>
  <dd><%= @experiencia.empresa_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              experiencias_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_experiencia_path(@experiencia), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              experiencia_path(@experiencia),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>