config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :empresas

  resources :ubicaciones

  resources :habilidades

  resources :categorias

  resources :experiencias

  resources :socios

  resources :laborales

  resources :permisos

  resources :perfiles

  resources :direcciones

  resources :usuarios

  resources :comunas

  resources :telefonos

  resources :slas

 resources :contratos do
     resources :calidades
  end 

 root 'index#index'
 

end

app/models/calidad.rb
class Calidad < ActiveRecord::Base
  belongs_to :sla
  belongs_to :contrato

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  belongs_to :laboral
end

app/models/comuna.rb
class Comuna < ActiveRecord::Base
	belongs_to :direccion
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
  belongs_to :usuario
  has_many :calidades
  has_many :slas, through: :calidades


end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :comuna
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
end

app/models/experiencia.rb
class Experiencia < ActiveRecord::Base
  belongs_to :laboral
  belongs_to :empresa
end

app/models/habilidad.rb
class Habilidad < ActiveRecord::Base
  belongs_to :usuario

# para aplicarlo en caso de que el usuario quiera crear otra habilidad (en no se ocupa actualmente)
  def habilidad_nombre
  	habilidad.try(:habilidad)
  end

  def habilidad_nombre=(habilidad)
  	  	self.habilidad = Habilidad.find_or_create_by_habilidad(habilidad) if habilidad.present?
  	  	#find_or_create_by_name
  end

end

app/models/laboral.rb
class Laboral < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
  belongs_to :empresa
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base
  belongs_to :perfil
end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
end

app/models/sla.rb
class Sla < ActiveRecord::Base
	  has_many :calidades
 	  has_many :contrato, through: :calidades
end

app/models/socio.rb
class Socio < ActiveRecord::Base
  belongs_to :usuario
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :usuario
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion

  def direccion_choose
  	direccion.try(:direccion)
  end

  def direccion_choose=(direccion)
  	  	self.direccion = Direccion.find_by_direccion(direccion) if direccion.present?
  	  	#find_or_create_by_name
  end

end

app/controllers/permisos_controller.rb
class PermisosController < ApplicationController
  before_action :set_permiso, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /permisos
  # GET /permisos.json
  def index
    @permisos = Permiso.all
  end

  # GET /permisos/1
  # GET /permisos/1.json
  def show
  end

  # GET /permisos/new
  def new
    @permiso = Permiso.new
  end

  # GET /permisos/1/edit
  def edit
  end

  # POST /permisos
  # POST /permisos.json
  def create
    @permiso = Permiso.new(permiso_params)

    respond_to do |format|
      if @permiso.save
        format.html { redirect_to @permiso, notice: 'Permiso fue exitosamente creado.' }
        format.json { render :show, status: :created, location: @permiso }
      else
        format.html { render :new }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permisos/1
  # PATCH/PUT /permisos/1.json
  def update
    respond_to do |format|
      if @permiso.update(permiso_params)
        format.html { redirect_to @permiso, notice: 'Permiso  fue exitosamente actualizado.' }
        format.json { render :show, status: :ok, location: @permiso }
      else
        format.html { render :edit }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permisos/1
  # DELETE /permisos/1.json
  def destroy
    @permiso.destroy
    respond_to do |format|
      format.html { redirect_to permisos_url, notice: 'Permiso fue exitosamente destruido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permiso
      @permiso = Permiso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permiso_params
      params.require(:permiso).permit(:permisos_id, :tipo, :descripcion, :perfil_id)
    end
end

app/helpers/comunas_helper.rb
module ComunasHelper
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/helpers/slas_helper.rb
module SlasHelper
end

app/helpers/socios_helper.rb
module SociosHelper
end

app/views/permisos/_form.html.erb
<%= form_for @permiso, :html => { :class => "form-horizontal permiso" } do |f| %>

    <% if @permiso.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@permiso.errors.count, "error") %> prohibited this permiso from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @permiso.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :permisos_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :permisos_id, :class => 'form-control' %>
    </div>
    <%= error_span(@permiso[:permisos_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :tipo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tipo, :class => 'form-control' %>
    </div>
    <%= error_span(@permiso[:tipo]) %>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descripcion, :class => 'form-control' %>
    </div>
    <%= error_span(@permiso[:descripcion]) %>
  </div>
  <div class="control-group">
    <%= f.label :perfil_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :perfil_id, :class => 'form-control' %>
    </div>
    <%= error_span(@permiso[:perfil_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            permisos_path, :class => 'btn btn-default' %>

<% end %>

app/views/permisos/edit.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permisos/index.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:permisos_id) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:perfil_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @permisos.each do |permiso| %>
      <tr>
        <td><%= link_to permiso.id, permiso_path(permiso) %></td>
        <td><%= permiso.permisos_id %></td>
        <td><%= permiso.tipo %></td>
        <td><%= permiso.descripcion %></td>
        <td><%= permiso.perfil_id %></td>
        <td><%=l permiso.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_permiso_path(permiso), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      permiso_path(permiso),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_permiso_path,
            :class => 'btn btn-primary' %>

app/views/permisos/new.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permisos/show.html.erb
<%- model_class = Permiso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:permisos_id) %>:</strong></dt>
  <dd><%= @permiso.permisos_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo) %>:</strong></dt>
  <dd><%= @permiso.tipo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @permiso.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:perfil_id) %>:</strong></dt>
  <dd><%= @permiso.perfil_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              permisos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_permiso_path(@permiso), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              permiso_path(@permiso),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>