config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :empresas

  resources :ubicaciones

  resources :habilidades

  resources :categorias

  resources :experiencias

  resources :socios

  resources :laborales

  resources :permisos

  resources :perfiles

  resources :direcciones

  resources :usuarios

  resources :comunas

  resources :telefonos

  resources :slas

 resources :contratos do
     resources :calidades
  end 

 root 'index#index'
 

end

app/models/calidad.rb
class Calidad < ActiveRecord::Base
  belongs_to :sla
  belongs_to :contrato

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  belongs_to :laboral
end

app/models/comuna.rb
class Comuna < ActiveRecord::Base
	belongs_to :direccion
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
  belongs_to :usuario
  has_many :calidades
  has_many :slas, through: :calidades


end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :comuna
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
end

app/models/experiencia.rb
class Experiencia < ActiveRecord::Base
  belongs_to :laboral
  belongs_to :empresa
end

app/models/habilidad.rb
class Habilidad < ActiveRecord::Base
  belongs_to :usuario

# para aplicarlo en caso de que el usuario quiera crear otra habilidad (en no se ocupa actualmente)
  def habilidad_nombre
  	habilidad.try(:habilidad)
  end

  def habilidad_nombre=(habilidad)
  	  	self.habilidad = Habilidad.find_or_create_by_habilidad(habilidad) if habilidad.present?
  	  	#find_or_create_by_name
  end

end

app/models/laboral.rb
class Laboral < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
  belongs_to :empresa
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base
  belongs_to :perfil
end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
end

app/models/sla.rb
class Sla < ActiveRecord::Base
	  has_many :calidades
 	  has_many :contrato, through: :calidades
end

app/models/socio.rb
class Socio < ActiveRecord::Base
  belongs_to :usuario
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :usuario
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion

  def direccion_choose
  	direccion.try(:direccion)
  end

  def direccion_choose=(direccion)
  	  	self.direccion = Direccion.find_by_direccion(direccion) if direccion.present?
  	  	#find_or_create_by_name
  end

end

app/controllers/comunas_controller.rb
class ComunasController < ApplicationController
  before_action :set_comuna, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /comunas
  # GET /comunas.json
  def index
    @comunas = Comuna.all
  end

  # GET /comunas/1
  # GET /comunas/1.json
  def show
  end

  # GET /comunas/new
  def new
    @comuna = Comuna.new
  end

  # GET /comunas/1/edit
  def edit
  end

  # POST /comunas
  # POST /comunas.json
  def create
    @comuna = Comuna.new(comuna_params)

    respond_to do |format|
      if @comuna.save
        format.html { redirect_to @comuna, notice: 'Comuna fue exitosamente creado.' }
        format.json { render :show, status: :created, location: @comuna }
      else
        format.html { render :new }
        format.json { render json: @comuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comunas/1
  # PATCH/PUT /comunas/1.json
  def update
    respond_to do |format|
      if @comuna.update(comuna_params)
        format.html { redirect_to @comuna, notice: 'Comuna  fue exitosamente actualizado.' }
        format.json { render :show, status: :ok, location: @comuna }
      else
        format.html { render :edit }
        format.json { render json: @comuna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comunas/1
  # DELETE /comunas/1.json
  def destroy
    @comuna.destroy
    respond_to do |format|
      format.html { redirect_to comunas_url, notice: 'Comuna fue exitosamente destruido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comuna
      @comuna = Comuna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comuna_params
      params.require(:comuna).permit(:comuna_id, :nombre, :region, :pais)
    end
end

app/helpers/comunas_helper.rb
module ComunasHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/helpers/slas_helper.rb
module SlasHelper
end

app/helpers/socios_helper.rb
module SociosHelper
end

app/views/comunas/_form.html.erb
<%= form_for @comuna, :html => { :class => "form-horizontal comuna" } do |f| %>

    <% if @comuna.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@comuna.errors.count, "error") %> prohibited this comuna from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @comuna.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :comuna_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comuna_id, :class => 'form-control' %>
    </div>
    <%= error_span(@comuna[:comuna_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'form-control' %>
    </div>
    <%= error_span(@comuna[:nombre]) %>
  </div>
  <div class="control-group">
    <%= f.label :region, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :region, :class => 'form-control' %>
    </div>
    <%= error_span(@comuna[:region]) %>
  </div>
  <div class="control-group">
    <%= f.label :pais, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pais, :class => 'form-control' %>
    </div>
    <%= error_span(@comuna[:pais]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            comunas_path, :class => 'btn btn-default' %>

<% end %>

app/views/comunas/edit.html.erb
<%- model_class = Comuna -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comunas/index.html.erb
<%- model_class = Comuna -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:comuna_id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%= model_class.human_attribute_name(:pais) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comunas.each do |comuna| %>
      <tr>
        <td><%= link_to comuna.id, comuna_path(comuna) %></td>
        <td><%= comuna.comuna_id %></td>
        <td><%= comuna.nombre %></td>
        <td><%= comuna.region %></td>
        <td><%= comuna.pais %></td>
        <td><%=l comuna.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comuna_path(comuna), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comuna_path(comuna),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comuna_path,
            :class => 'btn btn-primary' %>

app/views/comunas/new.html.erb
<%- model_class = Comuna -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comunas/show.html.erb
<%- model_class = Comuna -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:comuna_id) %>:</strong></dt>
  <dd><%= @comuna.comuna_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @comuna.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:region) %>:</strong></dt>
  <dd><%= @comuna.region %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pais) %>:</strong></dt>
  <dd><%= @comuna.pais %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              comunas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comuna_path(@comuna), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comuna_path(@comuna),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>