config/routes.rb
Rails.application.routes.draw do

  resources :pruebas

  resources :empresas

  resources :ubicaciones

  resources :habilidades

  resources :categorias

  resources :experiencias

  resources :socios

  resources :laborales

  resources :permisos

  resources :perfiles

  resources :direcciones

  resources :usuarios

  resources :comunas

  resources :telefonos

  resources :slas

 resources :contratos do
     resources :calidades
  end 

 root 'index#index'
 

end

app/models/calidad.rb
class Calidad < ActiveRecord::Base
  belongs_to :sla
  belongs_to :contrato

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  belongs_to :laboral
end

app/models/comuna.rb
class Comuna < ActiveRecord::Base
	belongs_to :direccion
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
  belongs_to :usuario
  has_many :calidades
  has_many :slas, through: :calidades


end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :comuna
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
end

app/models/experiencia.rb
class Experiencia < ActiveRecord::Base
  belongs_to :laboral
  belongs_to :empresa
end

app/models/habilidad.rb
class Habilidad < ActiveRecord::Base
  belongs_to :usuario

# para aplicarlo en caso de que el usuario quiera crear otra habilidad (en no se ocupa actualmente)
  def habilidad_nombre
  	habilidad.try(:habilidad)
  end

  def habilidad_nombre=(habilidad)
  	  	self.habilidad = Habilidad.find_or_create_by_habilidad(habilidad) if habilidad.present?
  	  	#find_or_create_by_name
  end

end

app/models/laboral.rb
class Laboral < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion
  belongs_to :usuario
  belongs_to :empresa
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :permisos
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base
  belongs_to :perfil
end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
end

app/models/sla.rb
class Sla < ActiveRecord::Base
	  has_many :calidades
 	  has_many :contrato, through: :calidades
end

app/models/socio.rb
class Socio < ActiveRecord::Base
  belongs_to :usuario
end

app/models/telefono.rb
class Telefono < ActiveRecord::Base
	belongs_to :usuario
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :telefono
  belongs_to :direccion

  def direccion_choose
  	direccion.try(:direccion)
  end

  def direccion_choose=(direccion)
  	  	self.direccion = Direccion.find_by_direccion(direccion) if direccion.present?
  	  	#find_or_create_by_name
  end

end

app/controllers/pruebas_controller.rb
class PruebasController < ApplicationController
  before_action :set_prueba, only: [:show, :edit, :update, :destroy]

  # GET /pruebas
  # GET /pruebas.json
  def index
    @pruebas = Prueba.all
  end

  # GET /pruebas/1
  # GET /pruebas/1.json
  def show
  end

  # GET /pruebas/new
  def new
    @prueba = Prueba.new
  end

  # GET /pruebas/1/edit
  def edit
  end

  # POST /pruebas
  # POST /pruebas.json
  def create
    @prueba = Prueba.new(prueba_params)

    respond_to do |format|
      if @prueba.save
        format.html { redirect_to @prueba, notice: 'Prueba was successfully created.' }
        format.json { render :show, status: :created, location: @prueba }
      else
        format.html { render :new }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pruebas/1
  # PATCH/PUT /pruebas/1.json
  def update
    respond_to do |format|
      if @prueba.update(prueba_params)
        format.html { redirect_to @prueba, notice: 'Prueba was successfully updated.' }
        format.json { render :show, status: :ok, location: @prueba }
      else
        format.html { render :edit }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pruebas/1
  # DELETE /pruebas/1.json
  def destroy
    @prueba.destroy
    respond_to do |format|
      format.html { redirect_to pruebas_url, notice: 'Prueba was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prueba
      @prueba = Prueba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prueba_params
      params.require(:prueba).permit(:datobinary, :datobollean, :datodate, :datodecimal, :datofloat, :datointeger, :datotimestamp, :datotext, :datostring, :datofecha)
    end
end

app/helpers/comunas_helper.rb
module ComunasHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/helpers/slas_helper.rb
module SlasHelper
end

app/helpers/socios_helper.rb
module SociosHelper
end

app/views/pruebas/_form.html.erb
<%= form_for(@prueba) do |f| %>
  <% if @prueba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prueba.errors.count, "error") %> prohibited this prueba from being saved:</h2>

      <ul>
      <% @prueba.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :datobinary %><br>
    <%= f.text_field :datobinary %>
  </div>
  <div class="field">
    <%= f.label :datobollean %><br>
    <%= f.check_box :datobollean %>
  </div>
  <div class="field">
    <%= f.label :datodate %><br>
    <%= f.date_select :datodate %>
  </div>
  <div class="field">
    <%= f.label :datodecimal %><br>
    <%= f.text_field :datodecimal %>
  </div>
  <div class="field">
    <%= f.label :datofloat %><br>
    <%= f.text_field :datofloat %>
  </div>
  <div class="field">
    <%= f.label :datointeger %><br>
    <%= f.number_field :datointeger %>
  </div>
  <div class="field">
    <%= f.label :datotimestamp %><br>
    <%= f.datetime_select :datotimestamp %>
  </div>
  <div class="field">
    <%= f.label :datotext %><br>
    <%= f.text_area :datotext %>
  </div>
  <div class="field">
    <%= f.label :datostring %><br>
    <%= f.text_field :datostring %>
  </div>
  <div class="field">
    <%= f.label :datofecha %><br>
    <%= f.datetime_select :datofecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pruebas/edit.html.erb
<h1>Editing prueba</h1>

<%= render 'form' %>

<%= link_to 'Show', @prueba %> |
<%= link_to 'Back', pruebas_path %>

app/views/pruebas/index.html.erb
<h1>Listing pruebas</h1>

<table>
  <thead>
    <tr>
      <th>Datobinary</th>
      <th>Datobollean</th>
      <th>Datodate</th>
      <th>Datodecimal</th>
      <th>Datofloat</th>
      <th>Datointeger</th>
      <th>Datotimestamp</th>
      <th>Datotext</th>
      <th>Datostring</th>
      <th>Datofecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pruebas.each do |prueba| %>
      <tr>
        <td><%= prueba.datobinary %></td>
        <td><%= prueba.datobollean %></td>
        <td><%= prueba.datodate %></td>
        <td><%= prueba.datodecimal %></td>
        <td><%= prueba.datofloat %></td>
        <td><%= prueba.datointeger %></td>
        <td><%= prueba.datotimestamp %></td>
        <td><%= prueba.datotext %></td>
        <td><%= prueba.datostring %></td>
        <td><%= prueba.datofecha %></td>
        <td><%= link_to 'Show', prueba %></td>
        <td><%= link_to 'Edit', edit_prueba_path(prueba) %></td>
        <td><%= link_to 'Destroy', prueba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prueba', new_prueba_path %>

app/views/pruebas/new.html.erb
<h1>New prueba</h1>

<%= render 'form' %>

<%= link_to 'Back', pruebas_path %>

app/views/pruebas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datobinary:</strong>
  <%= @prueba.datobinary %>
</p>

<p>
  <strong>Datobollean:</strong>
  <%= @prueba.datobollean %>
</p>

<p>
  <strong>Datodate:</strong>
  <%= @prueba.datodate %>
</p>

<p>
  <strong>Datodecimal:</strong>
  <%= @prueba.datodecimal %>
</p>

<p>
  <strong>Datofloat:</strong>
  <%= @prueba.datofloat %>
</p>

<p>
  <strong>Datointeger:</strong>
  <%= @prueba.datointeger %>
</p>

<p>
  <strong>Datotimestamp:</strong>
  <%= @prueba.datotimestamp %>
</p>

<p>
  <strong>Datotext:</strong>
  <%= @prueba.datotext %>
</p>

<p>
  <strong>Datostring:</strong>
  <%= @prueba.datostring %>
</p>

<p>
  <strong>Datofecha:</strong>
  <%= @prueba.datofecha %>
</p>

<%= link_to 'Edit', edit_prueba_path(@prueba) %> |
<%= link_to 'Back', pruebas_path %>